<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic\PushMsg;

use UnexpectedValueException;

/**
 * Protobuf type <code>im.logic.PushMsg.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>PUSH = 0;</code>
     */
    const PUSH = 0;
    /**
     * Generated from protobuf enum <code>ROOM = 1;</code>
     */
    const ROOM = 1;
    /**
     * Generated from protobuf enum <code>BROADCAST = 2;</code>
     */
    const BROADCAST = 2;

    private static $valueToName = [
        self::PUSH => 'PUSH',
        self::ROOM => 'ROOM',
        self::BROADCAST => 'BROADCAST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Im\Logic\PushMsg_Type::class);

