<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

namespace Im\Cloud;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.cloud.BroadcastReq</code>
 */
class BroadcastReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 protoOp = 1;</code>
     */
    private $protoOp = 0;
    /**
     * Generated from protobuf field <code>.im.cloud.Proto proto = 2;</code>
     */
    private $proto = null;
    /**
     * Generated from protobuf field <code>int32 speed = 3;</code>
     */
    private $speed = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protoOp
     *     @type \Im\Cloud\Proto $proto
     *     @type int $speed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cloud::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 protoOp = 1;</code>
     * @return int
     */
    public function getProtoOp()
    {
        return $this->protoOp;
    }

    /**
     * Generated from protobuf field <code>int32 protoOp = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtoOp($var)
    {
        GPBUtil::checkInt32($var);
        $this->protoOp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.im.cloud.Proto proto = 2;</code>
     * @return \Im\Cloud\Proto
     */
    public function getProto()
    {
        return $this->proto;
    }

    /**
     * Generated from protobuf field <code>.im.cloud.Proto proto = 2;</code>
     * @param \Im\Cloud\Proto $var
     * @return $this
     */
    public function setProto($var)
    {
        GPBUtil::checkMessage($var, \Im\Cloud\Proto::class);
        $this->proto = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 speed = 3;</code>
     * @return int
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * Generated from protobuf field <code>int32 speed = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeed($var)
    {
        GPBUtil::checkInt32($var);
        $this->speed = $var;

        return $this;
    }

}

