<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

namespace Im\Cloud;

use UnexpectedValueException;

/**
 * Protobuf type <code>im.cloud.Operation</code>
 */
class Operation
{
    /**
     * OpHandshake handshake
     *
     * Generated from protobuf enum <code>OpHandshake = 0;</code>
     */
    const OpHandshake = 0;
    /**
     * OpHandshakeReply handshake reply
     *
     * Generated from protobuf enum <code>OpHandshakeReply = 1;</code>
     */
    const OpHandshakeReply = 1;
    /**
     * OpHeartbeat heartbeat
     *
     * Generated from protobuf enum <code>OpHeartbeat = 2;</code>
     */
    const OpHeartbeat = 2;
    /**
     * OpHeartbeatReply heartbeat reply
     *
     * Generated from protobuf enum <code>OpHeartbeatReply = 3;</code>
     */
    const OpHeartbeatReply = 3;
    /**
     * OpSendMsg send message.
     *
     * Generated from protobuf enum <code>OpSendMsg = 4;</code>
     */
    const OpSendMsg = 4;
    /**
     * OpSendMsgReply  send message reply
     *
     * Generated from protobuf enum <code>OpSendMsgReply = 5;</code>
     */
    const OpSendMsgReply = 5;
    /**
     * OpDisconnectReply disconnect reply
     *
     * Generated from protobuf enum <code>OpDisconnectReply = 6;</code>
     */
    const OpDisconnectReply = 6;
    /**
     * OpAuth auth connnect
     *
     * Generated from protobuf enum <code>OpAuth = 7;</code>
     */
    const OpAuth = 7;
    /**
     * OpAuthReply auth connect reply
     *
     * Generated from protobuf enum <code>OpAuthReply = 8;</code>
     */
    const OpAuthReply = 8;
    /**
     * OpRaw raw message
     *
     * Generated from protobuf enum <code>OpRaw = 9;</code>
     */
    const OpRaw = 9;
    /**
     * OpProtoReady proto ready
     *
     * Generated from protobuf enum <code>OpProtoReady = 10;</code>
     */
    const OpProtoReady = 10;
    /**
     * OpProtoFinish proto finish
     *
     * Generated from protobuf enum <code>OpProtoFinish = 1;</code>
     */
    const OpProtoFinish = 1;
    /**
     * OpChangeRoom change room
     *
     * Generated from protobuf enum <code>OpChangeRoom = 12;</code>
     */
    const OpChangeRoom = 12;
    /**
     * OpChangeRoomReply change room reply
     *
     * Generated from protobuf enum <code>OpChangeRoomReply = 13;</code>
     */
    const OpChangeRoomReply = 13;
    /**
     * OpSub subscribe operation
     *
     * Generated from protobuf enum <code>OpSub = 14;</code>
     */
    const OpSub = 14;
    /**
     * OpSubReply subscribe operation
     *
     * Generated from protobuf enum <code>OpSubReply = 15;</code>
     */
    const OpSubReply = 15;
    /**
     * OpUnsub unsubscribe operation
     *
     * Generated from protobuf enum <code>OpUnsub = 16;</code>
     */
    const OpUnsub = 16;
    /**
     * OpUnsubReply unsubscribe operation reply
     *
     * Generated from protobuf enum <code>OpUnsubReply = 17;</code>
     */
    const OpUnsubReply = 17;

    private static $valueToName = [
        self::OpHandshake => 'OpHandshake',
        self::OpHandshakeReply => 'OpHandshakeReply',
        self::OpHeartbeat => 'OpHeartbeat',
        self::OpHeartbeatReply => 'OpHeartbeatReply',
        self::OpSendMsg => 'OpSendMsg',
        self::OpSendMsgReply => 'OpSendMsgReply',
        self::OpDisconnectReply => 'OpDisconnectReply',
        self::OpAuth => 'OpAuth',
        self::OpAuthReply => 'OpAuthReply',
        self::OpRaw => 'OpRaw',
        self::OpProtoReady => 'OpProtoReady',
        self::OpProtoFinish => 'OpProtoFinish',
        self::OpChangeRoom => 'OpChangeRoom',
        self::OpChangeRoomReply => 'OpChangeRoomReply',
        self::OpSub => 'OpSub',
        self::OpSubReply => 'OpSubReply',
        self::OpUnsub => 'OpUnsub',
        self::OpUnsubReply => 'OpUnsubReply',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

