<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

namespace Im\Cloud;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * v2.0.0
 * protocol
 *
 * Generated from protobuf message <code>im.cloud.Proto</code>
 */
class Proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ver = 1;</code>
     */
    private $ver = 0;
    /**
     * Generated from protobuf field <code>int32 op = 2;</code>
     */
    private $op = 0;
    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     */
    private $seq = 0;
    /**
     * Generated from protobuf field <code>bytes body = 4;</code>
     */
    private $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ver
     *     @type int $op
     *     @type int $seq
     *     @type string $body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cloud::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ver = 1;</code>
     * @return int
     */
    public function getVer()
    {
        return $this->ver;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVer($var)
    {
        GPBUtil::checkInt32($var);
        $this->ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 op = 2;</code>
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>int32 op = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkInt32($var);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>bytes body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

}

