language: php

php:
  - 7.0
  - 7.1

install:
  - wget https://github.com/swoole/swoole-src/archive/v2.1.1.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && cd swoole && phpize
  - ./configure --enable-coroutine && make -j$(nproc) && make install && cd ..

before_script:
  - composer update

script: composer test
