<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

namespace Im\Cloud;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.cloud.PushMsgReq</code>
 */
class PushMsgReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>int32 protoOp = 3;</code>
     */
    private $protoOp = 0;
    /**
     * Generated from protobuf field <code>.im.cloud.Proto proto = 2;</code>
     */
    private $proto = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $keys
     *     @type int $protoOp
     *     @type \Im\Cloud\Proto $proto
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cloud::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 protoOp = 3;</code>
     * @return int
     */
    public function getProtoOp()
    {
        return $this->protoOp;
    }

    /**
     * Generated from protobuf field <code>int32 protoOp = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProtoOp($var)
    {
        GPBUtil::checkInt32($var);
        $this->protoOp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.im.cloud.Proto proto = 2;</code>
     * @return \Im\Cloud\Proto
     */
    public function getProto()
    {
        return $this->proto;
    }

    /**
     * Generated from protobuf field <code>.im.cloud.Proto proto = 2;</code>
     * @param \Im\Cloud\Proto $var
     * @return $this
     */
    public function setProto($var)
    {
        GPBUtil::checkMessage($var, \Im\Cloud\Proto::class);
        $this->proto = $var;

        return $this;
    }

}

