<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

namespace Im\Cloud;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.cloud.RoomsReply</code>
 */
class RoomsReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, bool> rooms = 1;</code>
     */
    private $rooms;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $rooms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cloud::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, bool> rooms = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getRooms()
    {
        return $this->rooms;
    }

    /**
     * Generated from protobuf field <code>map<string, bool> rooms = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setRooms($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->rooms = $arr;

        return $this;
    }

}

