<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.logic.Backoff</code>
 */
class Backoff extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 MaxDelay = 1;</code>
     */
    private $MaxDelay = 0;
    /**
     * Generated from protobuf field <code>int32 BaseDelay = 2;</code>
     */
    private $BaseDelay = 0;
    /**
     * Generated from protobuf field <code>float Factor = 3;</code>
     */
    private $Factor = 0.0;
    /**
     * Generated from protobuf field <code>float Jitter = 4;</code>
     */
    private $Jitter = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $MaxDelay
     *     @type int $BaseDelay
     *     @type float $Factor
     *     @type float $Jitter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 MaxDelay = 1;</code>
     * @return int
     */
    public function getMaxDelay()
    {
        return $this->MaxDelay;
    }

    /**
     * Generated from protobuf field <code>int32 MaxDelay = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->MaxDelay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 BaseDelay = 2;</code>
     * @return int
     */
    public function getBaseDelay()
    {
        return $this->BaseDelay;
    }

    /**
     * Generated from protobuf field <code>int32 BaseDelay = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBaseDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->BaseDelay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Factor = 3;</code>
     * @return float
     */
    public function getFactor()
    {
        return $this->Factor;
    }

    /**
     * Generated from protobuf field <code>float Factor = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setFactor($var)
    {
        GPBUtil::checkFloat($var);
        $this->Factor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Jitter = 4;</code>
     * @return float
     */
    public function getJitter()
    {
        return $this->Jitter;
    }

    /**
     * Generated from protobuf field <code>float Jitter = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setJitter($var)
    {
        GPBUtil::checkFloat($var);
        $this->Jitter = $var;

        return $this;
    }

}

