<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.logic.DisconnectReply</code>
 */
class DisconnectReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool has = 1;</code>
     */
    private $has = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $has
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool has = 1;</code>
     * @return bool
     */
    public function getHas()
    {
        return $this->has;
    }

    /**
     * Generated from protobuf field <code>bool has = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setHas($var)
    {
        GPBUtil::checkBool($var);
        $this->has = $var;

        return $this;
    }

}

