<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

if (false) {
    /**
     * This class is deprecated. Use Im\Logic\PushMsg\Type instead.
     * @deprecated
     */
    class PushMsg_Type {}
}
class_exists(PushMsg\Type::class);
@trigger_error('Im\Logic\PushMsg_Type is deprecated and will be removed in the next major release. Use Im\Logic\PushMsg\Type instead', E_USER_DEPRECATED);

