<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * v2.0.0
 * protocol
 *
 * Generated from protobuf message <code>im.logic.PushMsg</code>
 */
class PushMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.im.logic.PushMsg.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int32 operation = 2;</code>
     */
    private $operation = 0;
    /**
     * Generated from protobuf field <code>int32 speed = 3;</code>
     */
    private $speed = 0;
    /**
     * Generated from protobuf field <code>string server = 4;</code>
     */
    private $server = '';
    /**
     * Generated from protobuf field <code>string room = 5;</code>
     */
    private $room = '';
    /**
     * Generated from protobuf field <code>repeated string keys = 6;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>bytes msg = 7;</code>
     */
    private $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int $operation
     *     @type int $speed
     *     @type string $server
     *     @type string $room
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $keys
     *     @type string $msg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.im.logic.PushMsg.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.im.logic.PushMsg.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Im\Logic\PushMsg_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 operation = 2;</code>
     * @return int
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Generated from protobuf field <code>int32 operation = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkInt32($var);
        $this->operation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 speed = 3;</code>
     * @return int
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * Generated from protobuf field <code>int32 speed = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeed($var)
    {
        GPBUtil::checkInt32($var);
        $this->speed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server = 4;</code>
     * @return string
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>string server = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->server = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room = 5;</code>
     * @return string
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Generated from protobuf field <code>string room = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkString($var, True);
        $this->room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes msg = 7;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>bytes msg = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, False);
        $this->msg = $var;

        return $this;
    }

}

