<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.logic.ConnectReq</code>
 */
class ConnectReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string server = 1;</code>
     */
    private $server = '';
    /**
     * Generated from protobuf field <code>string cookie = 2;</code>
     */
    private $cookie = '';
    /**
     * Generated from protobuf field <code>bytes token = 3;</code>
     */
    private $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $server
     *     @type string $cookie
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string server = 1;</code>
     * @return string
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>string server = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->server = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cookie = 2;</code>
     * @return string
     */
    public function getCookie()
    {
        return $this->cookie;
    }

    /**
     * Generated from protobuf field <code>string cookie = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCookie($var)
    {
        GPBUtil::checkString($var, True);
        $this->cookie = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes token = 3;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>bytes token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->token = $var;

        return $this;
    }

}

