<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.logic.ConnectReply</code>
 */
class ConnectReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 mid = 1;</code>
     */
    private $mid = 0;
    /**
     * Generated from protobuf field <code>string key = 2;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>string roomID = 3;</code>
     */
    private $roomID = '';
    /**
     * Generated from protobuf field <code>repeated int32 accepts = 4;</code>
     */
    private $accepts;
    /**
     * Generated from protobuf field <code>int64 heartbeat = 5;</code>
     */
    private $heartbeat = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $mid
     *     @type string $key
     *     @type string $roomID
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $accepts
     *     @type int|string $heartbeat
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 mid = 1;</code>
     * @return int|string
     */
    public function getMid()
    {
        return $this->mid;
    }

    /**
     * Generated from protobuf field <code>int64 mid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMid($var)
    {
        GPBUtil::checkInt64($var);
        $this->mid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roomID = 3;</code>
     * @return string
     */
    public function getRoomID()
    {
        return $this->roomID;
    }

    /**
     * Generated from protobuf field <code>string roomID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomID($var)
    {
        GPBUtil::checkString($var, True);
        $this->roomID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 accepts = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAccepts()
    {
        return $this->accepts;
    }

    /**
     * Generated from protobuf field <code>repeated int32 accepts = 4;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAccepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->accepts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 heartbeat = 5;</code>
     * @return int|string
     */
    public function getHeartbeat()
    {
        return $this->heartbeat;
    }

    /**
     * Generated from protobuf field <code>int64 heartbeat = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeartbeat($var)
    {
        GPBUtil::checkInt64($var);
        $this->heartbeat = $var;

        return $this;
    }

}

