<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.logic.NodesReq</code>
 */
class NodesReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     */
    private $platform = '';
    /**
     * Generated from protobuf field <code>string clientIP = 2;</code>
     */
    private $clientIP = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $platform
     *     @type string $clientIP
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientIP = 2;</code>
     * @return string
     */
    public function getClientIP()
    {
        return $this->clientIP;
    }

    /**
     * Generated from protobuf field <code>string clientIP = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIP($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientIP = $var;

        return $this;
    }

}

