<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic.proto

namespace Im\Logic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>im.logic.OnlineReply</code>
 */
class OnlineReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, int32> allRoomCount = 1;</code>
     */
    private $allRoomCount;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $allRoomCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, int32> allRoomCount = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAllRoomCount()
    {
        return $this->allRoomCount;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> allRoomCount = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAllRoomCount($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->allRoomCount = $arr;

        return $this;
    }

}

